---
title: "Analises"
author: "Helena"
date: "15/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Download de dados

Dados de clima de 2020: https://portal.inmet.gov.br/uploads/dadoshistoricos/2020.zip


```{r cars}
library(readr)
library(stringr)

ajustar_nomes=function(x){
  x%>%
    stringr::str_trim() %>%                           #Remove espaços em branco sobrando
    stringr::str_to_lower() %>%                       #Converte todas as strings para minusculo
    stringi::stri_trans_general("Latin-ASCII") %>% #Remove os acentos com a funcao criada acima
    stringr::str_replace_all("[/' '.()]", "_") %>%    #Substitui os caracteres especiais por "_"
    stringr::str_replace_all("_+", "_") %>%           #Substitui os caracteres especiais por "_"   
    stringr::str_replace("_$", "")                    #Substitui o caracter especiais por "_"
}

weather_site = "https://portal.inmet.gov.br/uploads/dadoshistoricos/2020.zip"
file_name = "INMET_S_PR_B806_COLOMBO_01-01-2020_A_31-12-2020.CSV"
linhas_dados_gerais = 8

    #nome_colunas = c("Data",	"Hora UTC",	"PRECIPITACAO TOTAL",	"PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO", "PRESSAO ATMOSFERICA MAX NA HORA ANT", "PRESSAO ATMOSFERICA MIN NA HORA ANT",	"RADIACAO GLOBAL",	"TEMPERATURA DO AR", "TEMPERATURA DO PONTO DE ORVALHO",	"TEMPERATURA MAX NA HORA ANT", "TEMPERATURA MIN NA HORA ANT", "TEMPERATURA ORVALHO MAX NA HORA ANT", "TEMPERATURA ORVALHO MIN NA HORA ANT",	"UMIDADE REL MAX NA HORA ANT", "UMIDADE REL MIN NA HORA ANT",	"UMIDADE RELATIVA DO AR", "VENTO DIRECAO HORARIA",	"VENTO RAJADA MAXIMA", "VENTO VELOCIDADE HORARIA")
    #nome_colunas
    #nome_colunas_ajustas = ajustar_nomes(nome_colunas)
    #nome_colunas_ajustas
    #class(nome_colunas_ajustas)

#temp <- tempfile()
#download.file(weather_site, temp)

#unzip(temp, file_name)

colombo <- read.csv2(file_name, sep = ";", dec = ",", skip = linhas_dados_gerais, row.names = NULL)
class(colombo)
View(colombo)

for (i in 1:19) {
  colnames(colombo)[i] <- ajustar_nomes(colnames(colombo)[i])
}



```

## Including Plots

You can also embed plots, for example:

```{r nomes}
library(stringr)

nomes=c('Aniversário', 'Situação', 'Raça', 'IMC', 'Tipo físico', 'tabaco por dia (cig/dia)', 'Alcool (dose/semana)', 'Drogas/g', 'Café/dia', 'Suco/dia')
nomes

ajustar_nomes=function(x){
  x%>%
    stringr::str_trim() %>%                           #Remove espaços em branco sobrando
    stringr::str_to_lower() %>%                       #Converte todas as strings para minusculo
    stringi::stri_trans_general("Latin-ASCII") %>% #Remove os acentos com a funcao criada acima
    stringr::str_replace_all("[/' '.()]", "_") %>%    #Substitui os caracteres especiais por "_"
    stringr::str_replace_all("_+", "_") %>%           #Substitui os caracteres especiais por "_"   
    stringr::str_replace("_$", "")                    #Substitui o caracter especiais por "_"
}

nomes=ajustar_nomes(nomes)

nomes

```

```{r pressure, echo=FALSE}
plot(pressure)

colnames(colombo)[1] <- "Data"
colnames(colombo)[2] <- "Hora UTC"
colnames(colombo)[3] <- "PRECIPITACAO TOTAL"
colnames(colombo)[4] <- "PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO"
colnames(colombo)[5] <- "PRESSAO ATMOSFERICA MAX NA HORA ANT"
colnames(colombo)[6] <- "PRESSAO ATMOSFERICA MIN NA HORA ANT"
colnames(colombo)[7] <- "RADIACAO GLOBAL"
colnames(colombo)[8] <- "TEMPERATURA DO AR"
colnames(colombo)[9] <- "TEMPERATURA DO PONTO DE ORVALHO"
colnames(colombo)[10] <- "TEMPERATURA MAX NA HORA ANT"
colnames(colombo)[11] <- "TEMPERATURA MIN NA HORA ANT"
colnames(colombo)[12] <- "TEMPERATURA ORVALHO MAX NA HORA ANT"
colnames(colombo)[13] <- "TEMPERATURA ORVALHO MIN NA HORA ANT"
colnames(colombo)[14] <- "UMIDADE REL MAX NA HORA ANT"
colnames(colombo)[15] <- "UMIDADE REL MIN NA HORA ANT"
colnames(colombo)[16] <- "UMIDADE RELATIVA DO AR"
colnames(colombo)[17] <- "VENTO DIREÇÃO HORARIA"
colnames(colombo)[18] <- "VENTO RAJADA MAXIMA"
colnames(colombo)[19] <- "VENTO VELOCIDADE HORARIA"
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
